# Generated by Django 5.1.3 on 2025-03-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='prep_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
