# Generated by Django 5.1.6 on 2025-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0010_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Canteen Staff'), ('owner', 'Canteen Owner')], default='student', max_length=10),
        ),
    ]
